name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build Debug
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Upload Artifact (linux)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ahq-lang-linux
        path: target/release/ahq-lang
    - name: Upload artifact (windows)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ahq-lang-windows.exe
        path: target/release/ahq-lang.exe
